name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Compilers
      run: |
        sudo apt-get update
        sudo apt-get install --yes build-essential
        sudo apt-get install --yes llvm-12 clang-12
        sudo apt-get install --yes pkgconf libelf-dev
        sudo apt-get install --yes bsdutils
        for tool in "clang" "llc" "llvm-strip"
        do
          sudo rm -f /usr/bin/$tool
          sudo ln -s /usr/bin/$tool-12 /usr/bin/$tool
        done
      shell: bash
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: make all
